# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1
# Use a package of configuration called an orb.
# orbs:
  # Declare a dependency on the welcome-orb
  # welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
# workflows:
  # Name the workflow "welcome"
  # welcome:
    # Run the welcome/run job in its own container
    # jobs:
      # - welcome/run
        
version: 2.1
jobs:
  deploy_dev:
    docker:
      - image: node:14.15.0
    working_directory: ~/Desktop/React/share_app
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN


# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   build:
#     jobs:
#       - run: npm install
#       - run: npm run build
